// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for GenerationModelType.
const (
	GenerationModelTypeAll   GenerationModelType = "all"
	GenerationModelTypeImage GenerationModelType = "image"
	GenerationModelTypeVideo GenerationModelType = "video"
)

// Valid indicates whether the value is a known member of the GenerationModelType enum.
func (e GenerationModelType) Valid() bool {
	switch e {
	case GenerationModelTypeAll:
		return true
	case GenerationModelTypeImage:
		return true
	case GenerationModelTypeVideo:
		return true
	default:
		return false
	}
}

// Defines values for ImageGenerationCostRequestQuality.
const (
	ImageGenerationCostRequestQualityN15K  ImageGenerationCostRequestQuality = "1.5K"
	ImageGenerationCostRequestQualityN1K   ImageGenerationCostRequestQuality = "1K"
	ImageGenerationCostRequestQualityN2K   ImageGenerationCostRequestQuality = "2K"
	ImageGenerationCostRequestQualityN4K   ImageGenerationCostRequestQuality = "4K"
	ImageGenerationCostRequestQualityN512p ImageGenerationCostRequestQuality = "512p"
)

// Valid indicates whether the value is a known member of the ImageGenerationCostRequestQuality enum.
func (e ImageGenerationCostRequestQuality) Valid() bool {
	switch e {
	case ImageGenerationCostRequestQualityN15K:
		return true
	case ImageGenerationCostRequestQualityN1K:
		return true
	case ImageGenerationCostRequestQualityN2K:
		return true
	case ImageGenerationCostRequestQualityN4K:
		return true
	case ImageGenerationCostRequestQualityN512p:
		return true
	default:
		return false
	}
}

// Defines values for ImageGenerationRequestQuality.
const (
	ImageGenerationRequestQualityN15K  ImageGenerationRequestQuality = "1.5K"
	ImageGenerationRequestQualityN1K   ImageGenerationRequestQuality = "1K"
	ImageGenerationRequestQualityN2K   ImageGenerationRequestQuality = "2K"
	ImageGenerationRequestQualityN4K   ImageGenerationRequestQuality = "4K"
	ImageGenerationRequestQualityN512p ImageGenerationRequestQuality = "512p"
)

// Valid indicates whether the value is a known member of the ImageGenerationRequestQuality enum.
func (e ImageGenerationRequestQuality) Valid() bool {
	switch e {
	case ImageGenerationRequestQualityN15K:
		return true
	case ImageGenerationRequestQualityN1K:
		return true
	case ImageGenerationRequestQualityN2K:
		return true
	case ImageGenerationRequestQualityN4K:
		return true
	case ImageGenerationRequestQualityN512p:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	Completed  JobStatus = "completed"
	Error      JobStatus = "error"
	Pending    JobStatus = "pending"
	Processing JobStatus = "processing"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Error:
		return true
	case Pending:
		return true
	case Processing:
		return true
	default:
		return false
	}
}

// Defines values for JobType.
const (
	ASSETPROCESSING JobType = "ASSET_PROCESSING"
	IMAGE           JobType = "IMAGE"
	IMAGEPRESET     JobType = "IMAGE_PRESET"
	UPSCALE         JobType = "UPSCALE"
	VIDEO           JobType = "VIDEO"
	VIDEOPRESET     JobType = "VIDEO_PRESET"
)

// Valid indicates whether the value is a known member of the JobType enum.
func (e JobType) Valid() bool {
	switch e {
	case ASSETPROCESSING:
		return true
	case IMAGE:
		return true
	case IMAGEPRESET:
		return true
	case UPSCALE:
		return true
	case VIDEO:
		return true
	case VIDEOPRESET:
		return true
	default:
		return false
	}
}

// Defines values for MediaModality.
const (
	MediaModalityAudio MediaModality = "audio"
	MediaModalityImage MediaModality = "image"
	MediaModalityVideo MediaModality = "video"
)

// Valid indicates whether the value is a known member of the MediaModality enum.
func (e MediaModality) Valid() bool {
	switch e {
	case MediaModalityAudio:
		return true
	case MediaModalityImage:
		return true
	case MediaModalityVideo:
		return true
	default:
		return false
	}
}

// Defines values for MediaSource.
const (
	Generated MediaSource = "generated"
	Uploaded  MediaSource = "uploaded"
)

// Valid indicates whether the value is a known member of the MediaSource enum.
func (e MediaSource) Valid() bool {
	switch e {
	case Generated:
		return true
	case Uploaded:
		return true
	default:
		return false
	}
}

// Defines values for VideoGenerationCostRequestDuration1.
const (
	VideoGenerationCostRequestDuration1Minus1 VideoGenerationCostRequestDuration1 = -1
)

// Valid indicates whether the value is a known member of the VideoGenerationCostRequestDuration1 enum.
func (e VideoGenerationCostRequestDuration1) Valid() bool {
	switch e {
	case VideoGenerationCostRequestDuration1Minus1:
		return true
	default:
		return false
	}
}

// Defines values for VideoGenerationCostRequestExtendDirection.
const (
	VideoGenerationCostRequestExtendDirectionBackward VideoGenerationCostRequestExtendDirection = "backward"
	VideoGenerationCostRequestExtendDirectionForward  VideoGenerationCostRequestExtendDirection = "forward"
)

// Valid indicates whether the value is a known member of the VideoGenerationCostRequestExtendDirection enum.
func (e VideoGenerationCostRequestExtendDirection) Valid() bool {
	switch e {
	case VideoGenerationCostRequestExtendDirectionBackward:
		return true
	case VideoGenerationCostRequestExtendDirectionForward:
		return true
	default:
		return false
	}
}

// Defines values for VideoGenerationRequestDuration1.
const (
	VideoGenerationRequestDuration1Minus1 VideoGenerationRequestDuration1 = -1
)

// Valid indicates whether the value is a known member of the VideoGenerationRequestDuration1 enum.
func (e VideoGenerationRequestDuration1) Valid() bool {
	switch e {
	case VideoGenerationRequestDuration1Minus1:
		return true
	default:
		return false
	}
}

// Defines values for VideoGenerationRequestExtendDirection.
const (
	VideoGenerationRequestExtendDirectionBackward VideoGenerationRequestExtendDirection = "backward"
	VideoGenerationRequestExtendDirectionForward  VideoGenerationRequestExtendDirection = "forward"
)

// Valid indicates whether the value is a known member of the VideoGenerationRequestExtendDirection enum.
func (e VideoGenerationRequestExtendDirection) Valid() bool {
	switch e {
	case VideoGenerationRequestExtendDirectionBackward:
		return true
	case VideoGenerationRequestExtendDirectionForward:
		return true
	default:
		return false
	}
}

// Defines values for VideoInputType.
const (
	EndFrame   VideoInputType = "end_frame"
	RefAudio   VideoInputType = "ref_audio"
	RefImage   VideoInputType = "ref_image"
	RefVideo   VideoInputType = "ref_video"
	StartFrame VideoInputType = "start_frame"
)

// Valid indicates whether the value is a known member of the VideoInputType enum.
func (e VideoInputType) Valid() bool {
	switch e {
	case EndFrame:
		return true
	case RefAudio:
		return true
	case RefImage:
		return true
	case RefVideo:
		return true
	case StartFrame:
		return true
	default:
		return false
	}
}

// CreditBalanceResponse defines model for CreditBalanceResponse.
type CreditBalanceResponse struct {
	OtherCredits        int `json:"other_credits"`
	SubscriptionCredits int `json:"subscription_credits"`
	TotalCredits        int `json:"total_credits"`
}

// GenerationCostResponse defines model for GenerationCostResponse.
type GenerationCostResponse struct {
	Credits     int     `json:"credits"`
	JobType     JobType `json:"jobType"`
	ListCredits *int    `json:"list_credits,omitempty"`
	ModelId     string  `json:"modelId"`
}

// GenerationModelCatalogResponse defines model for GenerationModelCatalogResponse.
type GenerationModelCatalogResponse struct {
	Models []map[string]interface{} `json:"models"`
}

// GenerationModelType defines model for GenerationModelType.
type GenerationModelType string

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	// Detail Either a pydantic validation error array or a plain string, depending on whether the backend raised this 422 via automatic request validation or a manual HTTPException. Decoded as raw JSON and interpreted at the call site.
	Detail *json.RawMessage `json:"detail,omitempty"`
}

// ImageGenerationCostRequest Cost-preflight variant of ImageGenerationRequest. The prompt does not
// affect the price and the preview is fetched before the user types, so it is
// optional here (the generation request still requires it).
type ImageGenerationCostRequest struct {
	AspectRatio *string                            `json:"aspect_ratio,omitempty"`
	Metadata    *map[string]interface{}            `json:"metadata,omitempty"`
	ModelId     string                             `json:"model_id"`
	NumOutputs  *int                               `json:"num_outputs,omitempty"`
	Prompt      *string                            `json:"prompt,omitempty"`
	Quality     *ImageGenerationCostRequestQuality `json:"quality,omitempty"`
	References  *[]ReferenceImage                  `json:"references,omitempty"`
	Seed        *int                               `json:"seed,omitempty"`
}

// ImageGenerationCostRequestQuality defines model for ImageGenerationCostRequest.Quality.
type ImageGenerationCostRequestQuality string

// ImageGenerationMetadata defines model for ImageGenerationMetadata.
type ImageGenerationMetadata struct {
	AspectRatio   *string                   `json:"aspectRatio,omitempty"`
	Inputs        *[]map[string]interface{} `json:"inputs,omitempty"`
	ModelId       *string                   `json:"modelId,omitempty"`
	PresetId      *string                   `json:"presetId,omitempty"`
	PresetVersion *int                      `json:"presetVersion,omitempty"`
	Prompt        *string                   `json:"prompt,omitempty"`
	Quality       *string                   `json:"quality,omitempty"`
	References    *[]map[string]interface{} `json:"references,omitempty"`
	Seed          *int                      `json:"seed,omitempty"`
}

// ImageGenerationRequest defines model for ImageGenerationRequest.
type ImageGenerationRequest struct {
	AspectRatio *string                        `json:"aspect_ratio,omitempty"`
	Metadata    *map[string]interface{}        `json:"metadata,omitempty"`
	ModelId     string                         `json:"model_id"`
	NumOutputs  *int                           `json:"num_outputs,omitempty"`
	Prompt      string                         `json:"prompt"`
	Quality     *ImageGenerationRequestQuality `json:"quality,omitempty"`
	References  *[]ReferenceImage              `json:"references,omitempty"`
	Seed        *int                           `json:"seed,omitempty"`
}

// ImageGenerationRequestQuality defines model for ImageGenerationRequest.Quality.
type ImageGenerationRequestQuality string

// JobCreateResponse defines model for JobCreateResponse.
type JobCreateResponse struct {
	JobId  string    `json:"job_id"`
	Status JobStatus `json:"status"`
}

// JobRecord defines model for JobRecord.
type JobRecord struct {
	CreatedAt     time.Time               `json:"created_at"`
	ErrorCode     *string                 `json:"error_code,omitempty"`
	ErrorMessage  *string                 `json:"error_message,omitempty"`
	JobId         string                  `json:"job_id"`
	JobType       JobType                 `json:"job_type"`
	LastUpdatedAt time.Time               `json:"last_updated_at"`
	Outputs       *[]MediaData            `json:"outputs,omitempty"`
	Payload       *map[string]interface{} `json:"payload,omitempty"`
	Status        JobStatus               `json:"status"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// JobType defines model for JobType.
type JobType string

// MediaData defines model for MediaData.
type MediaData struct {
	ContentType        string                        `json:"contentType"`
	CreatedAt          time.Time                     `json:"createdAt"`
	GenerationMetadata *MediaData_GenerationMetadata `json:"generationMetadata,omitempty"`
	IsFavorite         *bool                         `json:"isFavorite,omitempty"`
	JobId              *string                       `json:"jobId,omitempty"`
	LastFrameMediaId   *string                       `json:"lastFrameMediaId,omitempty"`
	MediaId            string                        `json:"mediaId"`
	Metadata           *MediaMetadata                `json:"metadata,omitempty"`
	Modality           MediaModality                 `json:"modality"`
	Source             MediaSource                   `json:"source"`
	UpdatedAt          time.Time                     `json:"updatedAt"`
	Url                string                        `json:"url"`
}

// MediaData_GenerationMetadata defines model for MediaData.GenerationMetadata.
type MediaData_GenerationMetadata struct {
	union json.RawMessage
}

// MediaMetadata defines model for MediaMetadata.
type MediaMetadata struct {
	DurationMs      *int    `json:"durationMs,omitempty"`
	FileName        *string `json:"fileName,omitempty"`
	Height          *int    `json:"height,omitempty"`
	Size            *int    `json:"size,omitempty"`
	ValidationError *string `json:"validationError,omitempty"`
	ValidationState *string `json:"validationState,omitempty"`
	Width           *int    `json:"width,omitempty"`
}

// MediaModality defines model for MediaModality.
type MediaModality string

// MediaSource defines model for MediaSource.
type MediaSource string

// ReferenceImage defines model for ReferenceImage.
type ReferenceImage struct {
	ContentType *string `json:"content_type,omitempty"`
	FileName    *string `json:"file_name,omitempty"`
	ImageBytes  *string `json:"image_bytes,omitempty"`
	ImageUrl    *string `json:"image_url,omitempty"`
	MediaId     *string `json:"media_id,omitempty"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for ValidationError.Loc.0.
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for ValidationError.Loc.1.
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// VideoGenerationCostRequest Cost-preflight variant of VideoGenerationRequest: the prompt does not
// affect the price, so the prompt-required rule does not apply here.
type VideoGenerationCostRequest struct {
	AspectRatio          *string                                    `json:"aspect_ratio,omitempty"`
	CharacterOrientation *string                                    `json:"character_orientation,omitempty"`
	Duration             *VideoGenerationCostRequest_Duration       `json:"duration,omitempty"`
	EnableAudio          *bool                                      `json:"enable_audio,omitempty"`
	ExtendDirection      *VideoGenerationCostRequestExtendDirection `json:"extend_direction,omitempty"`
	ExtendVideo          *bool                                      `json:"extend_video,omitempty"`
	Inputs               *[]VideoJobInput                           `json:"inputs,omitempty"`
	KeepReferenceAudio   *bool                                      `json:"keep_reference_audio,omitempty"`
	Metadata             *map[string]interface{}                    `json:"metadata,omitempty"`
	ModelId              string                                     `json:"model_id"`
	Prompt               *string                                    `json:"prompt,omitempty"`
	Resolution           *string                                    `json:"resolution,omitempty"`
	Seed                 *int                                       `json:"seed,omitempty"`
}

// VideoGenerationCostRequestDuration0 defines model for VideoGenerationCostRequest.Duration.0.
type VideoGenerationCostRequestDuration0 = int

// VideoGenerationCostRequestDuration1 defines model for VideoGenerationCostRequest.Duration.1.
type VideoGenerationCostRequestDuration1 int

// VideoGenerationCostRequest_Duration defines model for VideoGenerationCostRequest.Duration.
type VideoGenerationCostRequest_Duration struct {
	union json.RawMessage
}

// VideoGenerationCostRequestExtendDirection defines model for VideoGenerationCostRequest.ExtendDirection.
type VideoGenerationCostRequestExtendDirection string

// VideoGenerationMetadata defines model for VideoGenerationMetadata.
type VideoGenerationMetadata struct {
	AspectRatio          *string                   `json:"aspectRatio,omitempty"`
	CharacterOrientation *string                   `json:"characterOrientation,omitempty"`
	CharacterVoice       *map[string]interface{}   `json:"characterVoice,omitempty"`
	Duration             *int                      `json:"duration,omitempty"`
	EnableAudio          *bool                     `json:"enableAudio,omitempty"`
	Inputs               *[]map[string]interface{} `json:"inputs,omitempty"`
	KeepReferenceAudio   *bool                     `json:"keepReferenceAudio,omitempty"`
	ModelId              *string                   `json:"modelId,omitempty"`
	PresetId             *string                   `json:"presetId,omitempty"`
	PresetVersion        *int                      `json:"presetVersion,omitempty"`
	Prompt               *string                   `json:"prompt,omitempty"`
	Resolution           *string                   `json:"resolution,omitempty"`
	Seed                 *int                      `json:"seed,omitempty"`
}

// VideoGenerationRequest defines model for VideoGenerationRequest.
type VideoGenerationRequest struct {
	AspectRatio          *string                                `json:"aspect_ratio,omitempty"`
	CharacterOrientation *string                                `json:"character_orientation,omitempty"`
	Duration             *VideoGenerationRequest_Duration       `json:"duration,omitempty"`
	EnableAudio          *bool                                  `json:"enable_audio,omitempty"`
	ExtendDirection      *VideoGenerationRequestExtendDirection `json:"extend_direction,omitempty"`
	ExtendVideo          *bool                                  `json:"extend_video,omitempty"`
	Inputs               *[]VideoJobInput                       `json:"inputs,omitempty"`
	KeepReferenceAudio   *bool                                  `json:"keep_reference_audio,omitempty"`
	Metadata             *map[string]interface{}                `json:"metadata,omitempty"`
	ModelId              string                                 `json:"model_id"`
	Prompt               *string                                `json:"prompt,omitempty"`
	Resolution           *string                                `json:"resolution,omitempty"`
	Seed                 *int                                   `json:"seed,omitempty"`
}

// VideoGenerationRequestDuration0 defines model for VideoGenerationRequest.Duration.0.
type VideoGenerationRequestDuration0 = int

// VideoGenerationRequestDuration1 defines model for VideoGenerationRequest.Duration.1.
type VideoGenerationRequestDuration1 int

// VideoGenerationRequest_Duration defines model for VideoGenerationRequest.Duration.
type VideoGenerationRequest_Duration struct {
	union json.RawMessage
}

// VideoGenerationRequestExtendDirection defines model for VideoGenerationRequest.ExtendDirection.
type VideoGenerationRequestExtendDirection string

// VideoInputType defines model for VideoInputType.
type VideoInputType string

// VideoJobInput defines model for VideoJobInput.
type VideoJobInput struct {
	Attributes  *map[string]interface{} `json:"attributes,omitempty"`
	AudioUrl    *string                 `json:"audio_url,omitempty"`
	ContentType *string                 `json:"content_type,omitempty"`
	FileName    *string                 `json:"file_name,omitempty"`
	ImageBytes  *string                 `json:"image_bytes,omitempty"`
	ImageUrl    *string                 `json:"image_url,omitempty"`
	MediaId     *string                 `json:"media_id,omitempty"`
	Type        VideoInputType          `json:"type"`
	VideoUrl    *string                 `json:"video_url,omitempty"`
}

// GetJobV1JobsJobIdGetParams defines parameters for GetJobV1JobsJobIdGet.
type GetJobV1JobsJobIdGetParams struct {
	IncludePayload *bool `form:"includePayload,omitempty" json:"includePayload,omitempty"`
}

// GetGenerationModelsV1ModelsGenerationGetParams defines parameters for GetGenerationModelsV1ModelsGenerationGet.
type GetGenerationModelsV1ModelsGenerationGetParams struct {
	Type *GenerationModelType `form:"type,omitempty" json:"type,omitempty"`
}

// GetImageGenerationCostV1GenerationImageCostPostJSONRequestBody defines body for GetImageGenerationCostV1GenerationImageCostPost for application/json ContentType.
type GetImageGenerationCostV1GenerationImageCostPostJSONRequestBody = ImageGenerationCostRequest

// GetVideoGenerationCostV1GenerationVideoCostPostJSONRequestBody defines body for GetVideoGenerationCostV1GenerationVideoCostPost for application/json ContentType.
type GetVideoGenerationCostV1GenerationVideoCostPostJSONRequestBody = VideoGenerationCostRequest

// CreateImageJobV1ImagePostJSONRequestBody defines body for CreateImageJobV1ImagePost for application/json ContentType.
type CreateImageJobV1ImagePostJSONRequestBody = ImageGenerationRequest

// CreateVideoJobV1VideoPostJSONRequestBody defines body for CreateVideoJobV1VideoPost for application/json ContentType.
type CreateVideoJobV1VideoPostJSONRequestBody = VideoGenerationRequest

// AsImageGenerationMetadata returns the union data inside the MediaData_GenerationMetadata as a ImageGenerationMetadata
func (t MediaData_GenerationMetadata) AsImageGenerationMetadata() (ImageGenerationMetadata, error) {
	var body ImageGenerationMetadata
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageGenerationMetadata overwrites any union data inside the MediaData_GenerationMetadata as the provided ImageGenerationMetadata
func (t *MediaData_GenerationMetadata) FromImageGenerationMetadata(v ImageGenerationMetadata) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageGenerationMetadata performs a merge with any union data inside the MediaData_GenerationMetadata, using the provided ImageGenerationMetadata
func (t *MediaData_GenerationMetadata) MergeImageGenerationMetadata(v ImageGenerationMetadata) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVideoGenerationMetadata returns the union data inside the MediaData_GenerationMetadata as a VideoGenerationMetadata
func (t MediaData_GenerationMetadata) AsVideoGenerationMetadata() (VideoGenerationMetadata, error) {
	var body VideoGenerationMetadata
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVideoGenerationMetadata overwrites any union data inside the MediaData_GenerationMetadata as the provided VideoGenerationMetadata
func (t *MediaData_GenerationMetadata) FromVideoGenerationMetadata(v VideoGenerationMetadata) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVideoGenerationMetadata performs a merge with any union data inside the MediaData_GenerationMetadata, using the provided VideoGenerationMetadata
func (t *MediaData_GenerationMetadata) MergeVideoGenerationMetadata(v VideoGenerationMetadata) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MediaData_GenerationMetadata) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MediaData_GenerationMetadata) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsVideoGenerationCostRequestDuration0 returns the union data inside the VideoGenerationCostRequest_Duration as a VideoGenerationCostRequestDuration0
func (t VideoGenerationCostRequest_Duration) AsVideoGenerationCostRequestDuration0() (VideoGenerationCostRequestDuration0, error) {
	var body VideoGenerationCostRequestDuration0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVideoGenerationCostRequestDuration0 overwrites any union data inside the VideoGenerationCostRequest_Duration as the provided VideoGenerationCostRequestDuration0
func (t *VideoGenerationCostRequest_Duration) FromVideoGenerationCostRequestDuration0(v VideoGenerationCostRequestDuration0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVideoGenerationCostRequestDuration0 performs a merge with any union data inside the VideoGenerationCostRequest_Duration, using the provided VideoGenerationCostRequestDuration0
func (t *VideoGenerationCostRequest_Duration) MergeVideoGenerationCostRequestDuration0(v VideoGenerationCostRequestDuration0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVideoGenerationCostRequestDuration1 returns the union data inside the VideoGenerationCostRequest_Duration as a VideoGenerationCostRequestDuration1
func (t VideoGenerationCostRequest_Duration) AsVideoGenerationCostRequestDuration1() (VideoGenerationCostRequestDuration1, error) {
	var body VideoGenerationCostRequestDuration1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVideoGenerationCostRequestDuration1 overwrites any union data inside the VideoGenerationCostRequest_Duration as the provided VideoGenerationCostRequestDuration1
func (t *VideoGenerationCostRequest_Duration) FromVideoGenerationCostRequestDuration1(v VideoGenerationCostRequestDuration1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVideoGenerationCostRequestDuration1 performs a merge with any union data inside the VideoGenerationCostRequest_Duration, using the provided VideoGenerationCostRequestDuration1
func (t *VideoGenerationCostRequest_Duration) MergeVideoGenerationCostRequestDuration1(v VideoGenerationCostRequestDuration1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t VideoGenerationCostRequest_Duration) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *VideoGenerationCostRequest_Duration) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsVideoGenerationRequestDuration0 returns the union data inside the VideoGenerationRequest_Duration as a VideoGenerationRequestDuration0
func (t VideoGenerationRequest_Duration) AsVideoGenerationRequestDuration0() (VideoGenerationRequestDuration0, error) {
	var body VideoGenerationRequestDuration0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVideoGenerationRequestDuration0 overwrites any union data inside the VideoGenerationRequest_Duration as the provided VideoGenerationRequestDuration0
func (t *VideoGenerationRequest_Duration) FromVideoGenerationRequestDuration0(v VideoGenerationRequestDuration0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVideoGenerationRequestDuration0 performs a merge with any union data inside the VideoGenerationRequest_Duration, using the provided VideoGenerationRequestDuration0
func (t *VideoGenerationRequest_Duration) MergeVideoGenerationRequestDuration0(v VideoGenerationRequestDuration0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVideoGenerationRequestDuration1 returns the union data inside the VideoGenerationRequest_Duration as a VideoGenerationRequestDuration1
func (t VideoGenerationRequest_Duration) AsVideoGenerationRequestDuration1() (VideoGenerationRequestDuration1, error) {
	var body VideoGenerationRequestDuration1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVideoGenerationRequestDuration1 overwrites any union data inside the VideoGenerationRequest_Duration as the provided VideoGenerationRequestDuration1
func (t *VideoGenerationRequest_Duration) FromVideoGenerationRequestDuration1(v VideoGenerationRequestDuration1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVideoGenerationRequestDuration1 performs a merge with any union data inside the VideoGenerationRequest_Duration, using the provided VideoGenerationRequestDuration1
func (t *VideoGenerationRequest_Duration) MergeVideoGenerationRequestDuration1(v VideoGenerationRequestDuration1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t VideoGenerationRequest_Duration) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *VideoGenerationRequest_Duration) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetCreditsV1CreditsGet Get Credits
	//
	// Corresponds with GET /v1/credits (the `GetCreditsV1CreditsGet` operationId).
	GetCreditsV1CreditsGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetImageGenerationCostV1GenerationImageCostPostWithBody Get Image Generation Cost
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/generation/image/cost (the `GetImageGenerationCostV1GenerationImageCostPost` operationId).
	GetImageGenerationCostV1GenerationImageCostPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetImageGenerationCostV1GenerationImageCostPost Get Image Generation Cost
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/generation/image/cost (the `GetImageGenerationCostV1GenerationImageCostPost` operationId).
	GetImageGenerationCostV1GenerationImageCostPost(ctx context.Context, body GetImageGenerationCostV1GenerationImageCostPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVideoGenerationCostV1GenerationVideoCostPostWithBody Get Video Generation Cost
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/generation/video/cost (the `GetVideoGenerationCostV1GenerationVideoCostPost` operationId).
	GetVideoGenerationCostV1GenerationVideoCostPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVideoGenerationCostV1GenerationVideoCostPost Get Video Generation Cost
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/generation/video/cost (the `GetVideoGenerationCostV1GenerationVideoCostPost` operationId).
	GetVideoGenerationCostV1GenerationVideoCostPost(ctx context.Context, body GetVideoGenerationCostV1GenerationVideoCostPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateImageJobV1ImagePostWithBody Create Image Job
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/image (the `CreateImageJobV1ImagePost` operationId).
	CreateImageJobV1ImagePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateImageJobV1ImagePost Create Image Job
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/image (the `CreateImageJobV1ImagePost` operationId).
	CreateImageJobV1ImagePost(ctx context.Context, body CreateImageJobV1ImagePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetJobV1JobsJobIdGet Get Job
	//
	// Corresponds with GET /v1/jobs/{job_id} (the `GetJobV1JobsJobIdGet` operationId).
	GetJobV1JobsJobIdGet(ctx context.Context, jobId string, params *GetJobV1JobsJobIdGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGenerationModelsV1ModelsGenerationGet Get Generation Models
	//
	// Corresponds with GET /v1/models/generation (the `GetGenerationModelsV1ModelsGenerationGet` operationId).
	GetGenerationModelsV1ModelsGenerationGet(ctx context.Context, params *GetGenerationModelsV1ModelsGenerationGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateVideoJobV1VideoPostWithBody Create Video Job
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/video (the `CreateVideoJobV1VideoPost` operationId).
	CreateVideoJobV1VideoPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateVideoJobV1VideoPost Create Video Job
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/video (the `CreateVideoJobV1VideoPost` operationId).
	CreateVideoJobV1VideoPost(ctx context.Context, body CreateVideoJobV1VideoPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetCreditsV1CreditsGet Get Credits
//
// Corresponds with GET /v1/credits (the `GetCreditsV1CreditsGet` operationId).
func (c *Client) GetCreditsV1CreditsGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCreditsV1CreditsGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetImageGenerationCostV1GenerationImageCostPostWithBody Get Image Generation Cost
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/generation/image/cost (the `GetImageGenerationCostV1GenerationImageCostPost` operationId).
func (c *Client) GetImageGenerationCostV1GenerationImageCostPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetImageGenerationCostV1GenerationImageCostPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetImageGenerationCostV1GenerationImageCostPost Get Image Generation Cost
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/generation/image/cost (the `GetImageGenerationCostV1GenerationImageCostPost` operationId).
func (c *Client) GetImageGenerationCostV1GenerationImageCostPost(ctx context.Context, body GetImageGenerationCostV1GenerationImageCostPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetImageGenerationCostV1GenerationImageCostPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetVideoGenerationCostV1GenerationVideoCostPostWithBody Get Video Generation Cost
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/generation/video/cost (the `GetVideoGenerationCostV1GenerationVideoCostPost` operationId).
func (c *Client) GetVideoGenerationCostV1GenerationVideoCostPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVideoGenerationCostV1GenerationVideoCostPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetVideoGenerationCostV1GenerationVideoCostPost Get Video Generation Cost
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/generation/video/cost (the `GetVideoGenerationCostV1GenerationVideoCostPost` operationId).
func (c *Client) GetVideoGenerationCostV1GenerationVideoCostPost(ctx context.Context, body GetVideoGenerationCostV1GenerationVideoCostPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVideoGenerationCostV1GenerationVideoCostPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateImageJobV1ImagePostWithBody Create Image Job
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/image (the `CreateImageJobV1ImagePost` operationId).
func (c *Client) CreateImageJobV1ImagePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateImageJobV1ImagePostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateImageJobV1ImagePost Create Image Job
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/image (the `CreateImageJobV1ImagePost` operationId).
func (c *Client) CreateImageJobV1ImagePost(ctx context.Context, body CreateImageJobV1ImagePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateImageJobV1ImagePostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetJobV1JobsJobIdGet Get Job
//
// Corresponds with GET /v1/jobs/{job_id} (the `GetJobV1JobsJobIdGet` operationId).
func (c *Client) GetJobV1JobsJobIdGet(ctx context.Context, jobId string, params *GetJobV1JobsJobIdGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetJobV1JobsJobIdGetRequest(c.Server, jobId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetGenerationModelsV1ModelsGenerationGet Get Generation Models
//
// Corresponds with GET /v1/models/generation (the `GetGenerationModelsV1ModelsGenerationGet` operationId).
func (c *Client) GetGenerationModelsV1ModelsGenerationGet(ctx context.Context, params *GetGenerationModelsV1ModelsGenerationGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGenerationModelsV1ModelsGenerationGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateVideoJobV1VideoPostWithBody Create Video Job
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/video (the `CreateVideoJobV1VideoPost` operationId).
func (c *Client) CreateVideoJobV1VideoPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateVideoJobV1VideoPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateVideoJobV1VideoPost Create Video Job
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/video (the `CreateVideoJobV1VideoPost` operationId).
func (c *Client) CreateVideoJobV1VideoPost(ctx context.Context, body CreateVideoJobV1VideoPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateVideoJobV1VideoPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCreditsV1CreditsGetRequest constructs an http.Request for the GetCreditsV1CreditsGet method
func NewGetCreditsV1CreditsGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/credits")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetImageGenerationCostV1GenerationImageCostPostRequest calls the generic GetImageGenerationCostV1GenerationImageCostPost builder with application/json body
func NewGetImageGenerationCostV1GenerationImageCostPostRequest(server string, body GetImageGenerationCostV1GenerationImageCostPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetImageGenerationCostV1GenerationImageCostPostRequestWithBody(server, "application/json", bodyReader)
}

// NewGetImageGenerationCostV1GenerationImageCostPostRequestWithBody constructs an http.Request for the GetImageGenerationCostV1GenerationImageCostPost method, with any body, and a specified content type
func NewGetImageGenerationCostV1GenerationImageCostPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/generation/image/cost")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetVideoGenerationCostV1GenerationVideoCostPostRequest calls the generic GetVideoGenerationCostV1GenerationVideoCostPost builder with application/json body
func NewGetVideoGenerationCostV1GenerationVideoCostPostRequest(server string, body GetVideoGenerationCostV1GenerationVideoCostPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetVideoGenerationCostV1GenerationVideoCostPostRequestWithBody(server, "application/json", bodyReader)
}

// NewGetVideoGenerationCostV1GenerationVideoCostPostRequestWithBody constructs an http.Request for the GetVideoGenerationCostV1GenerationVideoCostPost method, with any body, and a specified content type
func NewGetVideoGenerationCostV1GenerationVideoCostPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/generation/video/cost")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateImageJobV1ImagePostRequest calls the generic CreateImageJobV1ImagePost builder with application/json body
func NewCreateImageJobV1ImagePostRequest(server string, body CreateImageJobV1ImagePostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateImageJobV1ImagePostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateImageJobV1ImagePostRequestWithBody constructs an http.Request for the CreateImageJobV1ImagePost method, with any body, and a specified content type
func NewCreateImageJobV1ImagePostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/image")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetJobV1JobsJobIdGetRequest constructs an http.Request for the GetJobV1JobsJobIdGet method
func NewGetJobV1JobsJobIdGetRequest(server string, jobId string, params *GetJobV1JobsJobIdGetParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "job_id", jobId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.IncludePayload != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "includePayload", *params.IncludePayload, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetGenerationModelsV1ModelsGenerationGetRequest constructs an http.Request for the GetGenerationModelsV1ModelsGenerationGet method
func NewGetGenerationModelsV1ModelsGenerationGetRequest(server string, params *GetGenerationModelsV1ModelsGenerationGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/models/generation")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "type", *params.Type, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateVideoJobV1VideoPostRequest calls the generic CreateVideoJobV1VideoPost builder with application/json body
func NewCreateVideoJobV1VideoPostRequest(server string, body CreateVideoJobV1VideoPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateVideoJobV1VideoPostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateVideoJobV1VideoPostRequestWithBody constructs an http.Request for the CreateVideoJobV1VideoPost method, with any body, and a specified content type
func NewCreateVideoJobV1VideoPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/video")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetCreditsV1CreditsGetWithResponse Get Credits
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/credits (the `GetCreditsV1CreditsGet` operationId).
	GetCreditsV1CreditsGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCreditsV1CreditsGetResponse, error)

	// GetImageGenerationCostV1GenerationImageCostPostWithBodyWithResponse Get Image Generation Cost
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/generation/image/cost (the `GetImageGenerationCostV1GenerationImageCostPost` operationId).
	GetImageGenerationCostV1GenerationImageCostPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetImageGenerationCostV1GenerationImageCostPostResponse, error)

	// GetImageGenerationCostV1GenerationImageCostPostWithResponse Get Image Generation Cost
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/generation/image/cost (the `GetImageGenerationCostV1GenerationImageCostPost` operationId).
	GetImageGenerationCostV1GenerationImageCostPostWithResponse(ctx context.Context, body GetImageGenerationCostV1GenerationImageCostPostJSONRequestBody, reqEditors ...RequestEditorFn) (*GetImageGenerationCostV1GenerationImageCostPostResponse, error)

	// GetVideoGenerationCostV1GenerationVideoCostPostWithBodyWithResponse Get Video Generation Cost
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/generation/video/cost (the `GetVideoGenerationCostV1GenerationVideoCostPost` operationId).
	GetVideoGenerationCostV1GenerationVideoCostPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetVideoGenerationCostV1GenerationVideoCostPostResponse, error)

	// GetVideoGenerationCostV1GenerationVideoCostPostWithResponse Get Video Generation Cost
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/generation/video/cost (the `GetVideoGenerationCostV1GenerationVideoCostPost` operationId).
	GetVideoGenerationCostV1GenerationVideoCostPostWithResponse(ctx context.Context, body GetVideoGenerationCostV1GenerationVideoCostPostJSONRequestBody, reqEditors ...RequestEditorFn) (*GetVideoGenerationCostV1GenerationVideoCostPostResponse, error)

	// CreateImageJobV1ImagePostWithBodyWithResponse Create Image Job
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/image (the `CreateImageJobV1ImagePost` operationId).
	CreateImageJobV1ImagePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateImageJobV1ImagePostResponse, error)

	// CreateImageJobV1ImagePostWithResponse Create Image Job
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/image (the `CreateImageJobV1ImagePost` operationId).
	CreateImageJobV1ImagePostWithResponse(ctx context.Context, body CreateImageJobV1ImagePostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateImageJobV1ImagePostResponse, error)

	// GetJobV1JobsJobIdGetWithResponse Get Job
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/jobs/{job_id} (the `GetJobV1JobsJobIdGet` operationId).
	GetJobV1JobsJobIdGetWithResponse(ctx context.Context, jobId string, params *GetJobV1JobsJobIdGetParams, reqEditors ...RequestEditorFn) (*GetJobV1JobsJobIdGetResponse, error)

	// GetGenerationModelsV1ModelsGenerationGetWithResponse Get Generation Models
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/models/generation (the `GetGenerationModelsV1ModelsGenerationGet` operationId).
	GetGenerationModelsV1ModelsGenerationGetWithResponse(ctx context.Context, params *GetGenerationModelsV1ModelsGenerationGetParams, reqEditors ...RequestEditorFn) (*GetGenerationModelsV1ModelsGenerationGetResponse, error)

	// CreateVideoJobV1VideoPostWithBodyWithResponse Create Video Job
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/video (the `CreateVideoJobV1VideoPost` operationId).
	CreateVideoJobV1VideoPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateVideoJobV1VideoPostResponse, error)

	// CreateVideoJobV1VideoPostWithResponse Create Video Job
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/video (the `CreateVideoJobV1VideoPost` operationId).
	CreateVideoJobV1VideoPostWithResponse(ctx context.Context, body CreateVideoJobV1VideoPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateVideoJobV1VideoPostResponse, error)
}

type GetCreditsV1CreditsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CreditBalanceResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetCreditsV1CreditsGetResponse) GetJSON200() *CreditBalanceResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetCreditsV1CreditsGetResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCreditsV1CreditsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCreditsV1CreditsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCreditsV1CreditsGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetImageGenerationCostV1GenerationImageCostPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GenerationCostResponse
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *HTTPValidationError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetImageGenerationCostV1GenerationImageCostPostResponse) GetJSON200() *GenerationCostResponse {
	return r.JSON200
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r GetImageGenerationCostV1GenerationImageCostPostResponse) GetJSON422() *HTTPValidationError {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r GetImageGenerationCostV1GenerationImageCostPostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetImageGenerationCostV1GenerationImageCostPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetImageGenerationCostV1GenerationImageCostPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetImageGenerationCostV1GenerationImageCostPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetVideoGenerationCostV1GenerationVideoCostPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GenerationCostResponse
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *HTTPValidationError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetVideoGenerationCostV1GenerationVideoCostPostResponse) GetJSON200() *GenerationCostResponse {
	return r.JSON200
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r GetVideoGenerationCostV1GenerationVideoCostPostResponse) GetJSON422() *HTTPValidationError {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r GetVideoGenerationCostV1GenerationVideoCostPostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetVideoGenerationCostV1GenerationVideoCostPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVideoGenerationCostV1GenerationVideoCostPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetVideoGenerationCostV1GenerationVideoCostPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateImageJobV1ImagePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *JobCreateResponse
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *HTTPValidationError
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r CreateImageJobV1ImagePostResponse) GetJSON202() *JobCreateResponse {
	return r.JSON202
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r CreateImageJobV1ImagePostResponse) GetJSON422() *HTTPValidationError {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r CreateImageJobV1ImagePostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateImageJobV1ImagePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateImageJobV1ImagePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateImageJobV1ImagePostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetJobV1JobsJobIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JobRecord
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *HTTPValidationError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetJobV1JobsJobIdGetResponse) GetJSON200() *JobRecord {
	return r.JSON200
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r GetJobV1JobsJobIdGetResponse) GetJSON422() *HTTPValidationError {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r GetJobV1JobsJobIdGetResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetJobV1JobsJobIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetJobV1JobsJobIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetJobV1JobsJobIdGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetGenerationModelsV1ModelsGenerationGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GenerationModelCatalogResponse
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *HTTPValidationError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetGenerationModelsV1ModelsGenerationGetResponse) GetJSON200() *GenerationModelCatalogResponse {
	return r.JSON200
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r GetGenerationModelsV1ModelsGenerationGetResponse) GetJSON422() *HTTPValidationError {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r GetGenerationModelsV1ModelsGenerationGetResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetGenerationModelsV1ModelsGenerationGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGenerationModelsV1ModelsGenerationGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetGenerationModelsV1ModelsGenerationGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateVideoJobV1VideoPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *JobCreateResponse
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *HTTPValidationError
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r CreateVideoJobV1VideoPostResponse) GetJSON202() *JobCreateResponse {
	return r.JSON202
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r CreateVideoJobV1VideoPostResponse) GetJSON422() *HTTPValidationError {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r CreateVideoJobV1VideoPostResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateVideoJobV1VideoPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateVideoJobV1VideoPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateVideoJobV1VideoPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetCreditsV1CreditsGetWithResponse Get Credits
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/credits (the `GetCreditsV1CreditsGet` operationId).
func (c *ClientWithResponses) GetCreditsV1CreditsGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCreditsV1CreditsGetResponse, error) {
	rsp, err := c.GetCreditsV1CreditsGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCreditsV1CreditsGetResponse(rsp)
}

// GetImageGenerationCostV1GenerationImageCostPostWithBodyWithResponse Get Image Generation Cost
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/generation/image/cost (the `GetImageGenerationCostV1GenerationImageCostPost` operationId).
func (c *ClientWithResponses) GetImageGenerationCostV1GenerationImageCostPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetImageGenerationCostV1GenerationImageCostPostResponse, error) {
	rsp, err := c.GetImageGenerationCostV1GenerationImageCostPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetImageGenerationCostV1GenerationImageCostPostResponse(rsp)
}

// GetImageGenerationCostV1GenerationImageCostPostWithResponse Get Image Generation Cost
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/generation/image/cost (the `GetImageGenerationCostV1GenerationImageCostPost` operationId).
func (c *ClientWithResponses) GetImageGenerationCostV1GenerationImageCostPostWithResponse(ctx context.Context, body GetImageGenerationCostV1GenerationImageCostPostJSONRequestBody, reqEditors ...RequestEditorFn) (*GetImageGenerationCostV1GenerationImageCostPostResponse, error) {
	rsp, err := c.GetImageGenerationCostV1GenerationImageCostPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetImageGenerationCostV1GenerationImageCostPostResponse(rsp)
}

// GetVideoGenerationCostV1GenerationVideoCostPostWithBodyWithResponse Get Video Generation Cost
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/generation/video/cost (the `GetVideoGenerationCostV1GenerationVideoCostPost` operationId).
func (c *ClientWithResponses) GetVideoGenerationCostV1GenerationVideoCostPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetVideoGenerationCostV1GenerationVideoCostPostResponse, error) {
	rsp, err := c.GetVideoGenerationCostV1GenerationVideoCostPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVideoGenerationCostV1GenerationVideoCostPostResponse(rsp)
}

// GetVideoGenerationCostV1GenerationVideoCostPostWithResponse Get Video Generation Cost
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/generation/video/cost (the `GetVideoGenerationCostV1GenerationVideoCostPost` operationId).
func (c *ClientWithResponses) GetVideoGenerationCostV1GenerationVideoCostPostWithResponse(ctx context.Context, body GetVideoGenerationCostV1GenerationVideoCostPostJSONRequestBody, reqEditors ...RequestEditorFn) (*GetVideoGenerationCostV1GenerationVideoCostPostResponse, error) {
	rsp, err := c.GetVideoGenerationCostV1GenerationVideoCostPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVideoGenerationCostV1GenerationVideoCostPostResponse(rsp)
}

// CreateImageJobV1ImagePostWithBodyWithResponse Create Image Job
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/image (the `CreateImageJobV1ImagePost` operationId).
func (c *ClientWithResponses) CreateImageJobV1ImagePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateImageJobV1ImagePostResponse, error) {
	rsp, err := c.CreateImageJobV1ImagePostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateImageJobV1ImagePostResponse(rsp)
}

// CreateImageJobV1ImagePostWithResponse Create Image Job
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/image (the `CreateImageJobV1ImagePost` operationId).
func (c *ClientWithResponses) CreateImageJobV1ImagePostWithResponse(ctx context.Context, body CreateImageJobV1ImagePostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateImageJobV1ImagePostResponse, error) {
	rsp, err := c.CreateImageJobV1ImagePost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateImageJobV1ImagePostResponse(rsp)
}

// GetJobV1JobsJobIdGetWithResponse Get Job
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/jobs/{job_id} (the `GetJobV1JobsJobIdGet` operationId).
func (c *ClientWithResponses) GetJobV1JobsJobIdGetWithResponse(ctx context.Context, jobId string, params *GetJobV1JobsJobIdGetParams, reqEditors ...RequestEditorFn) (*GetJobV1JobsJobIdGetResponse, error) {
	rsp, err := c.GetJobV1JobsJobIdGet(ctx, jobId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetJobV1JobsJobIdGetResponse(rsp)
}

// GetGenerationModelsV1ModelsGenerationGetWithResponse Get Generation Models
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/models/generation (the `GetGenerationModelsV1ModelsGenerationGet` operationId).
func (c *ClientWithResponses) GetGenerationModelsV1ModelsGenerationGetWithResponse(ctx context.Context, params *GetGenerationModelsV1ModelsGenerationGetParams, reqEditors ...RequestEditorFn) (*GetGenerationModelsV1ModelsGenerationGetResponse, error) {
	rsp, err := c.GetGenerationModelsV1ModelsGenerationGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGenerationModelsV1ModelsGenerationGetResponse(rsp)
}

// CreateVideoJobV1VideoPostWithBodyWithResponse Create Video Job
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/video (the `CreateVideoJobV1VideoPost` operationId).
func (c *ClientWithResponses) CreateVideoJobV1VideoPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateVideoJobV1VideoPostResponse, error) {
	rsp, err := c.CreateVideoJobV1VideoPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateVideoJobV1VideoPostResponse(rsp)
}

// CreateVideoJobV1VideoPostWithResponse Create Video Job
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/video (the `CreateVideoJobV1VideoPost` operationId).
func (c *ClientWithResponses) CreateVideoJobV1VideoPostWithResponse(ctx context.Context, body CreateVideoJobV1VideoPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateVideoJobV1VideoPostResponse, error) {
	rsp, err := c.CreateVideoJobV1VideoPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateVideoJobV1VideoPostResponse(rsp)
}

// ParseGetCreditsV1CreditsGetResponse parses an HTTP response from a GetCreditsV1CreditsGetWithResponse call
func ParseGetCreditsV1CreditsGetResponse(rsp *http.Response) (*GetCreditsV1CreditsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCreditsV1CreditsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreditBalanceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetImageGenerationCostV1GenerationImageCostPostResponse parses an HTTP response from a GetImageGenerationCostV1GenerationImageCostPostWithResponse call
func ParseGetImageGenerationCostV1GenerationImageCostPostResponse(rsp *http.Response) (*GetImageGenerationCostV1GenerationImageCostPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetImageGenerationCostV1GenerationImageCostPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GenerationCostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetVideoGenerationCostV1GenerationVideoCostPostResponse parses an HTTP response from a GetVideoGenerationCostV1GenerationVideoCostPostWithResponse call
func ParseGetVideoGenerationCostV1GenerationVideoCostPostResponse(rsp *http.Response) (*GetVideoGenerationCostV1GenerationVideoCostPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVideoGenerationCostV1GenerationVideoCostPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GenerationCostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCreateImageJobV1ImagePostResponse parses an HTTP response from a CreateImageJobV1ImagePostWithResponse call
func ParseCreateImageJobV1ImagePostResponse(rsp *http.Response) (*CreateImageJobV1ImagePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateImageJobV1ImagePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest JobCreateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetJobV1JobsJobIdGetResponse parses an HTTP response from a GetJobV1JobsJobIdGetWithResponse call
func ParseGetJobV1JobsJobIdGetResponse(rsp *http.Response) (*GetJobV1JobsJobIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetJobV1JobsJobIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobRecord
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetGenerationModelsV1ModelsGenerationGetResponse parses an HTTP response from a GetGenerationModelsV1ModelsGenerationGetWithResponse call
func ParseGetGenerationModelsV1ModelsGenerationGetResponse(rsp *http.Response) (*GetGenerationModelsV1ModelsGenerationGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGenerationModelsV1ModelsGenerationGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GenerationModelCatalogResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCreateVideoJobV1VideoPostResponse parses an HTTP response from a CreateVideoJobV1VideoPostWithResponse call
func ParseCreateVideoJobV1VideoPostResponse(rsp *http.Response) (*CreateVideoJobV1VideoPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateVideoJobV1VideoPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest JobCreateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
